version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_DB=nakama
      - POSTGRES_USER=${POSGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSGRES_PASSWORD}
    volumes:
      - data:/var/lib/postgresql/data
    expose:
      - "8080"
      - "5432"
    ports:
      - "5432:5432"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSGRES_USERNAME}", "-d", "nakama"]
      interval: 3s
      timeout: 3s
      retries: 5
  nakama:
    container_name: nakama
    image: registry.heroiclabs.com/heroiclabs/nakama:3.26.0
    platform: ${DOCKER_PLATFORM:-linux/amd64}  # Default to amd64 if not set
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          /nakama/nakama migrate up --database.address ${POSGRES_USERNAME}:${POSGRES_PASSWORD}@postgres:5432/nakama &&
          exec /nakama/nakama --name nakama1 --database.address ${POSGRES_USERNAME}:${POSGRES_PASSWORD}@postgres:5432/nakama --logger.level DEBUG --session.token_expiry_sec 7200 --console.username ${NAKAMA_ADMIN_USERNAME} --console.password ${NAKAMA_ADMIN_PASSWORD} --session.encryption_key ${NAKAMA_SESSION_ENCRYPTION_KEY} --session.refresh_encryption_key ${NAKAMA_SESSION_REFRESH_ENCRYPTION_KEY} --socket.server_key ${NAKAMA_SOCKET_SERVER_KEY} --runtime.http_key ${NAKAMA_RUNTIME_HTTP_KEY}
    restart: always
    links:
      - "postgres:db"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/nakama/data
    expose:
      - "7349"
      - "7350"
      - "7351"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "/nakama/nakama", "healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    container_name: web-server
    build: ./node-js
    ports:
      - "443:443"
    volumes:
      - ./node-js/public:/app/public
    depends_on:
      - nakama
volumes:
  data: