document.addEventListener("DOMContentLoaded", () => {
    const message = document.getElementById("message");
    if (message) {
        message.textContent = "This message is generated by TypeScript!";
    }
});